version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "3000:8080"
    volumes:
      - ./app/src/:/go/src
    tty: true
    depends_on:
      - redis
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
